In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Automobile_data.csv")

In [ ]:
df.shape

(61, 10)

In [ ]:
df.columns

Index(['index', 'company', 'body-style', 'wheel-base', 'length', 'engine-type',
       'num-of-cylinders', 'horsepower', 'average-mileage', 'price'],
      dtype='object')

In [ ]:
df.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [ ]:
df.tail(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

In [ ]:
df.describe()

,index,wheel-base,length,horsepower,average-mileage,price
count,61.000000,61.000000,61.000000,61.000000,61.000000,58.000000
mean,40.885246,98.481967,173.098361,107.852459,25.803279,15387.000000
std,25.429706,6.679234,14.021846,53.524398,8.129821,11320.259841
min,0.000000,88.400000,141.100000,48.000000,13.000000,5151.000000
25%,18.000000,94.500000,159.100000,68.000000,19.000000,6808.500000
50%,39.000000,96.300000,171.200000,100.000000,25.000000,11095.000000
75%,61.000000,101.200000,177.300000,123.000000,31.000000,18120.500000
max,88.000000,120.900000,208.100000,288.000000,47.000000,45400.000000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["engine-type"]= df['engine-type'].replace("dohcv","dohc")

In [ ]:
df["body-style"].value_counts()

body-style
sedan          32
hatchback      15
wagon           9
convertible     3
hardtop         2
Name: count, dtype: int64

In [ ]:
df["company"] = df["company"].str.title().str.strip()
df["body-style"] = df["body-style"].str.title().str.strip()

In [ ]:
df.isnull().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [ ]:
df[df["price"].isnull()]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
22,31,Isuzu,Sedan,94.5,155.9,ohc,four,70,38,NaN
23,32,Isuzu,Sedan,94.5,155.9,ohc,four,70,38,NaN
47,63,Porsche,Hatchback,98.4,175.7,dohc,eight,288,17,NaN

In [ ]:
df[(df["company"]=="Isuzu") & (df["body-style"]=="Sedan")]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
21,30,Isuzu,Sedan,94.3,170.7,ohc,four,78,24,6785.0
22,31,Isuzu,Sedan,94.5,155.9,ohc,four,70,38,NaN
23,32,Isuzu,Sedan,94.5,155.9,ohc,four,70,38,NaN

In [ ]:
df.loc[(df["company"]=="Isuzu") & (df["body-style"]=="Sedan"),"price"].fillna(6785.0)

21    6785.0
22    6785.0
23    6785.0
Name: price, dtype: float64

In [ ]:
df.groupby(["company","body-style"])["price"].mean()

company        body-style
Alfa-Romero    Convertible    14997.500000
               Hatchback      16500.000000
Audi           Sedan          15550.000000
               Wagon          18920.000000
Bmw            Sedan          27213.333333
Chevrolet      Hatchback       5723.000000
               Sedan           6575.000000
Dodge          Hatchback       6303.000000
Honda          Sedan          11645.000000
               Wagon           7295.000000
Isuzu          Sedan           6785.000000
Jaguar         Sedan          34600.000000
Mazda          Hatchback       7482.500000
               Sedan          18344.000000
Mercedes-Benz  Hardtop        45400.000000
               Sedan          33256.000000
               Wagon          28248.000000
Mitsubishi     Hatchback       5789.000000
               Sedan           7589.000000
Nissan         Sedan           8524.000000
               Wagon           7349.000000
Porsche        Convertible    37028.000000
               Hardtop        34028.000000
               Hatchback               NaN
Toyota         Hatchback       6058.000000
               Wagon           9836.000000
Volkswagen     Sedan           8435.000000
Volvo          Sedan          12940.000000
               Wagon          13415.000000
Name: price, dtype: float64

In [ ]:
df['price'] = df["price"].interpolate(method = "linear")

In [ ]:
df[df["company"] == "Porsche"]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
45,61,Porsche,Hardtop,89.5,168.9,ohcf,six,207,17,34028.0
46,62,Porsche,Convertible,89.5,168.9,ohcf,six,207,17,37028.0
47,63,Porsche,Hatchback,98.4,175.7,dohc,eight,288,17,21188.0

In [ ]:
df.isnull().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               0
dtype: int64

In [ ]:
df.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,Alfa-Romero,Convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,Alfa-Romero,Convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,Alfa-Romero,Hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,Audi,Sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,Audi,Sedan,99.4,176.6,ohc,five,115,18,17450.0

In [ ]:
df.tail(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,Volkswagen,Sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,Volkswagen,Sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,Volkswagen,Sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,Volvo,Sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,Volvo,Wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.sort_values(by="price",ascending=False).head(1)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,Mercedes-Benz,Hardtop,112.0,199.2,ohcv,eight,184,14,45400.0

In [ ]:
df[df["company"]=="Toyota"]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,Toyota,Hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,Toyota,Hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,Toyota,Hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,Toyota,Wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,Toyota,Wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,Toyota,Wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,Toyota,Wagon,104.5,187.8,dohc,six,156,19,15750.0

In [ ]:
df["company"].value_counts()

company
Toyota           7
Bmw              6
Mazda            5
Nissan           5
Mercedes-Benz    4
Audi             4
Volkswagen       4
Mitsubishi       4
Chevrolet        3
Jaguar           3
Isuzu            3
Honda            3
Porsche          3
Alfa-Romero      3
Dodge            2
Volvo            2
Name: count, dtype: int64

In [ ]:
df.groupby("company")["price"].max()

company
Alfa-Romero      16500.000000
Audi             18920.000000
Bmw              41315.000000
Chevrolet         6575.000000
Dodge             6377.000000
Honda            12945.000000
Isuzu            23761.666667
Jaguar           36000.000000
Mazda            18344.000000
Mercedes-Benz    45400.000000
Mitsubishi        8189.000000
Nissan           13499.000000
Porsche          37028.000000
Toyota           15750.000000
Volkswagen        9995.000000
Volvo            13415.000000
Name: price, dtype: float64

In [ ]:
df.groupby("company")["average-mileage"].mean().sort_values(ascending=False)

company
Chevrolet        41.000000
Isuzu            33.333333
Volkswagen       31.750000
Nissan           31.400000
Dodge            31.000000
Mitsubishi       29.500000
Toyota           28.714286
Mazda            28.000000
Honda            26.333333
Volvo            23.000000
Alfa-Romero      20.333333
Audi             20.000000
Bmw              19.000000
Mercedes-Benz    18.000000
Porsche          17.000000
Jaguar           14.333333
Name: average-mileage, dtype: float64

In [ ]:
df.sort_values(by="price",ascending=False)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,Mercedes-Benz,Hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,14,Bmw,Sedan,103.5,193.8,ohc,six,182,16,41315.0
34,46,Mercedes-Benz,Sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,62,Porsche,Convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,15,Bmw,Sedan,110.0,197.0,ohc,six,182,15,36880.0
...,...,...,...,...,...,...,...,...,...,...
28,37,Mazda,Hatchback,93.1,159.1,ohc,four,68,31,6095.0
36,49,Mitsubishi,Hatchback,93.7,157.3,ohc,four,68,37,5389.0
48,66,Toyota,Hatchback,95.7,158.7,ohc,four,62,35,5348.0
27,36,Mazda,Hatchback,93.1,159.1,ohc,four,68,30,5195.0
13,16,Chevrolet,Hatchback,88.4,141.1,l,three,48,47,5151.0

In [ ]:
GermanCars= {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
df1 = pd.DataFrame(GermanCars)
df2 = pd.DataFrame(japaneseCars)
df3 = pd.concat([df1,df2])
df3

       Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
0       Toyota   29995
1        Honda   23600
2       Nissan   61500
3  Mitsubishi    58900

In [ ]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
df4 = pd.DataFrame(Car_Price)
df5 = pd.DataFrame(car_Horsepower)
df6 = pd.merge(df4,df5,on = "Company")
df6

  Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

In [ ]:
df.to_csv("Automobile_data_cleaned.csv")